"""
Generate AI exposure scores for all Australian occupations.

This script assigns AI exposure scores (0-10) based on the occupation's
description, tasks, and nature of work. Scores follow the same rubric
used in score.py (the LLM-based scorer).

Can be replaced by running score.py with an OpenRouter API key for
LLM-generated scores with detailed rationales.

Usage:
    python3 generate_scores.py
"""

import json
import os

# Scoring rules based on occupation characteristics.
# Each occupation is scored considering:
# - Whether work is primarily digital vs physical
# - Degree of routine vs creative/judgement-based tasks
# - Need for physical presence and manual skill
# - Interpersonal/caring components
# - Current AI capability in the domain

SCORES = {
    # === MANAGERS (1xxx) ===
    "1111": (7, "Chief executives perform predominantly knowledge work — strategic planning, policy formulation, and organisational direction — all of which are digital and increasingly AI-augmentable. However, leadership, stakeholder relationships, and high-stakes decision-making provide some protection."),
    "1112": (7, "General managers coordinate operations through digital communication, planning, and analysis. AI can assist with reporting, forecasting, and operational decisions, but human judgement and leadership remain essential."),
    "1113": (5, "Legislators require public trust, political judgement, and constituency relationships. While policy analysis can be AI-assisted, the core political and representational work requires human presence and judgement."),
    "1211": (2, "Aquaculture farming involves hands-on management of fish stocks, water quality, and physical infrastructure in variable environments. AI may assist with monitoring but cannot replace physical farm work."),
    "1212": (2, "Crop farming is primarily physical outdoor work — planting, tending, harvesting. Precision agriculture and AI monitoring are growing, but the core manual and environmental work remains human-dependent."),
    "1213": (2, "Livestock farming requires physical presence with animals, hands-on animal husbandry, and work in unpredictable outdoor environments. AI has minimal impact on core duties."),
    "1214": (2, "Mixed farming combines crop and livestock work, both highly physical. AI may help with farm management software but doesn't touch the core hands-on work."),
    "1311": (7, "Advertising and sales management involves strategy, campaign planning, and market analysis — all increasingly AI-augmentable. AI can generate content, analyse markets, and optimise campaigns, though client relationships remain important."),
    "1321": (7, "Corporate services management is predominantly knowledge work involving planning, compliance, and administration — areas where AI tools are already proving highly capable."),
    "1322": (7, "Finance management involves financial analysis, budgeting, forecasting, and reporting — all digital tasks where AI excels. Human oversight and strategic judgement remain important."),
    "1323": (7, "HR management combines strategic planning and policy development (highly AI-augmentable) with interpersonal elements like employee relations and leadership that provide some protection."),
    "1324": (7, "Policy and planning managers do predominantly digital knowledge work — research, analysis, policy drafting — all areas where AI is rapidly improving. Strategic judgement and stakeholder management offer some insulation."),
    "1325": (7, "R&D management involves coordinating research agendas and innovation strategies. While AI can accelerate research itself, directing and prioritising research still requires human expertise."),
    "1331": (4, "Construction managers split time between on-site supervision (physical presence required) and planning/scheduling/documentation (increasingly AI-augmentable). The physical site presence component provides protection."),
    "1332": (6, "Engineering managers oversee technical projects with significant digital planning and analysis components. Site visits and technical oversight provide some physical presence requirements."),
    "1333": (6, "Import/export and wholesale management involves supply chain coordination, market analysis, and logistics — increasingly AI-optimisable — though relationship management and negotiation remain human skills."),
    "1334": (5, "Manufacturing managers oversee physical production processes while also handling planning and coordination. The physical plant presence requirement provides moderate protection."),
    "1335": (5, "Production managers need physical presence on production floors while also doing planning and scheduling that AI can assist with. The split between physical and digital work provides moderate exposure."),
    "1336": (7, "Supply chain and procurement management is heavily data-driven — demand forecasting, logistics optimisation, and vendor analysis are all areas where AI excels."),
    "1341": (4, "Child care centre management combines administrative tasks (AI-augmentable) with hands-on supervision and interpersonal care of children. The caring and physical presence components provide significant protection."),
    "1342": (5, "Health and welfare services management involves both administrative planning (AI-augmentable) and direct service oversight requiring human empathy and judgement."),
    "1343": (5, "School principals combine educational leadership and community engagement (requiring human presence) with administrative tasks that AI can increasingly handle."),
    "1344": (6, "Education managers handle curriculum planning, policy development, and institutional administration — predominantly digital knowledge work with some need for interpersonal leadership."),
    "1351": (7, "ICT managers work entirely in digital domains — planning technology strategy, overseeing systems, and managing technical teams. AI is already transforming how this work is done."),
    "1391": (3, "Military officers require physical presence, leadership under pressure, and real-time decision-making in unpredictable environments. While AI assists with intelligence and planning, core military leadership is human."),
    "1392": (3, "Senior NCOs operate in physical military environments requiring hands-on leadership, training, and operational execution. AI has limited impact on core duties."),
    "1399": (6, "Other specialist managers typically perform knowledge work — analysis, planning, and coordination — with varying degrees of physical presence requirements."),
    "1411": (4, "Cafe and restaurant managers split between on-floor hospitality (physical presence, customer interaction) and administration (rostering, ordering, finances) where AI can help."),
    "1412": (3, "Caravan park and camping ground managers need constant physical presence for site maintenance, guest services, and outdoor facility management."),
    "1413": (4, "Hotel managers combine guest-facing hospitality (physical presence) with operational management (increasingly AI-augmentable through revenue management, booking systems, etc.)."),
    "1414": (4, "Licensed club management requires physical presence for venue operations and patron interaction, though administrative and financial tasks can be AI-assisted."),
    "1419": (4, "Accommodation and hospitality managers need physical presence for guest services while benefiting from AI in administrative and operational tasks."),
    "1421": (5, "Retail managers combine floor management and customer service (physical) with inventory, staffing, and merchandising analysis (increasingly AI-driven)."),
    "1491": (3, "Fitness and sports centre managers require physical presence for facility oversight, member interaction, and operations management in physical environments."),
    "1492": (8, "Call centre management is heavily data-driven — workforce scheduling, call routing, quality monitoring, and customer analytics. AI is already automating many of the underlying call centre functions."),
    "1493": (6, "Conference and event organisers do significant digital planning and coordination, though event execution requires physical presence and real-time problem-solving."),
    "1494": (5, "Transport services managers combine logistics coordination (highly AI-augmentable) with physical fleet and personnel oversight."),
    "1499": (5, "Other hospitality and service managers typically require physical presence while also performing administrative tasks that AI can assist with."),

    # === PROFESSIONALS (2xxx) ===
    "2111": (3, "Actors, dancers, and entertainers perform live physical/creative work requiring human presence, emotional expression, and audience connection. AI-generated content is emerging but live performance remains distinctly human."),
    "2112": (3, "Music professionals create and perform through physical instruments and voice. While AI can generate music, live performance, teaching, and creative collaboration remain human activities."),
    "2113": (6, "Photography involves both creative vision and technical execution. AI image generation is advancing rapidly, though event/portrait photography requiring physical presence has more protection."),
    "2114": (4, "Visual artists and craftspeople create physical works requiring manual skill and creative vision. While AI can generate digital art, physical craftsmanship remains human."),
    "2121": (6, "Media producers and presenters combine creative direction (increasingly AI-augmentable) with on-screen/on-air presence (human-dependent). The digital content creation side is highly exposed."),
    "2122": (9, "Authors, book editors, and script editors work entirely in digital text — AI can already draft, edit, and generate written content at scale. This is one of the most exposed professional occupations."),
    "2123": (5, "Film and stage directors require creative vision, leadership, and on-set presence. While AI assists with pre-production and post-production, live direction remains human."),
    "2124": (9, "Journalists and writers produce digital text content — reporting, analysis, opinion. AI can already generate news articles, summaries, and written content, making this highly exposed."),
    "2211": (8, "Accountants perform predominantly digital work — financial analysis, compliance, tax preparation, and reporting. AI and automation are already transforming accounting, with routine tasks being automated at scale."),
    "2212": (8, "Auditors and company secretaries perform digital analysis, compliance checking, and documentation — all areas where AI is rapidly improving. Pattern detection in auditing is a natural AI application."),
    "2221": (7, "Financial brokers perform market analysis, client advisory, and transaction execution — all increasingly AI-augmentable. Relationship management provides some protection."),
    "2222": (8, "Financial dealers work in fully digital environments — trading, market analysis, risk assessment. Algorithmic and AI-driven trading is already dominant in many markets."),
    "2223": (8, "Financial investment advisers perform portfolio analysis, risk assessment, and market research — all digital tasks where AI excels. Robo-advisors are already disrupting this space."),
    "2231": (7, "HR professionals handle recruitment, performance management, and workforce planning — increasingly AI-augmented through screening tools, analytics, and automated processes. Interpersonal elements provide some protection."),
    "2232": (7, "ICT trainers deliver training in digital domains. AI-generated tutorials, personalised learning, and interactive systems are rapidly emerging as alternatives."),
    "2233": (7, "Training and development professionals design and deliver programs — content creation is highly AI-augmentable, though in-person facilitation and needs assessment offer some protection."),
    "2241": (8, "Actuaries, mathematicians, and statisticians perform quantitative analysis, modelling, and risk assessment — all digital, computational tasks where AI excels."),
    "2242": (6, "Archivists and curators combine digital cataloguing and research (AI-augmentable) with physical collection management and exhibition work (requiring human presence and judgement)."),
    "2243": (8, "Economists perform research, data analysis, modelling, and policy writing — all digital knowledge work where AI is increasingly capable."),
    "2244": (8, "Intelligence and policy analysts perform research, data analysis, and report writing — predominantly digital work where AI can process information and generate insights at scale."),
    "2245": (6, "Land economists and valuers combine data analysis (AI-augmentable) with physical property inspections and local market knowledge requiring human presence."),
    "2246": (7, "Librarians perform information management, research assistance, and cataloguing — increasingly automated through digital systems and AI search capabilities. Community engagement aspects provide some protection."),
    "2247": (8, "Management and organisation analysts perform consulting, process analysis, and report writing — predominantly digital knowledge work highly suited to AI augmentation."),
    "2249": (7, "Other information and organisation professionals typically perform digital knowledge work — research, analysis, and information management — with varying AI exposure."),
    "2251": (8, "Advertising and marketing professionals create campaigns, analyse markets, and produce content — all areas where AI is rapidly advancing in content generation, targeting, and analytics."),
    "2252": (7, "ICT sales professionals combine technical knowledge with sales relationships. AI assists with technical proposals and market analysis, but relationship-building provides protection."),
    "2253": (8, "Public relations professionals create communications, manage media, and craft messaging — predominantly digital content work where AI can generate press releases, analyse sentiment, and manage responses."),
    "2254": (6, "Technical sales representatives combine product knowledge with in-person client relationships and demonstrations. The relationship and physical demonstration aspects provide moderate protection."),
    "2311": (3, "Air transport professionals (pilots) operate complex machinery requiring physical presence, real-time decision-making, and regulatory compliance. While autopilot exists, human oversight remains critical for safety."),
    "2312": (3, "Marine transport professionals operate vessels requiring physical presence, navigation skills, and real-time environmental response. Automation assists but cannot replace human presence."),
    "2321": (7, "Architects combine creative design (increasingly AI-augmentable through generative design) with client relationships and site work. The design component is highly digital and exposed."),
    "2322": (5, "Surveyors combine fieldwork (physical measurement, site visits) with digital analysis and mapping. The physical component provides moderate protection."),
    "2323": (7, "Fashion, industrial, and jewellery designers create designs — an increasingly AI-augmentable creative process, especially for digital design tools. Physical prototyping provides some protection."),
    "2324": (9, "Graphic and web designers work entirely in digital domains — visual design, layout, web interfaces. AI image generation and design tools are advancing extremely rapidly."),
    "2325": (6, "Interior designers combine digital design work (AI-augmentable) with client consultations and physical site assessments. The in-person and spatial components provide moderate protection."),
    "2326": (6, "Urban and regional planners combine data analysis and policy writing (AI-augmentable) with community consultation and site assessment (requiring human presence)."),
    "2331": (6, "Chemical engineers combine technical analysis and simulation (AI-augmentable) with laboratory and plant-based work requiring physical presence."),
    "2332": (6, "Civil engineering involves design calculations and documentation (increasingly AI-augmentable) alongside site inspections and project oversight requiring physical presence."),
    "2333": (6, "Electrical engineers combine digital design and analysis (AI-augmentable) with physical installation oversight and testing."),
    "2334": (7, "Electronics engineers work significantly in digital design, simulation, and testing — areas where AI is increasingly capable. Physical prototyping provides some protection."),
    "2335": (6, "Industrial and mechanical engineers combine design and analysis (AI-augmentable) with physical manufacturing oversight and testing."),
    "2336": (5, "Mining engineers work in physical mining environments requiring on-site presence, though planning and analysis components are increasingly digital and AI-augmentable."),
    "2339": (6, "Other engineering professionals typically combine digital analysis and design (AI-augmentable) with varying degrees of physical site work."),
    "2341": (6, "Agricultural scientists combine laboratory and field research (physical) with data analysis and report writing (AI-augmentable)."),
    "2342": (6, "Chemists and food scientists split between laboratory work (physical) and data analysis, research, and reporting (increasingly AI-augmentable)."),
    "2343": (6, "Environmental scientists combine fieldwork and sampling (physical) with data analysis, modelling, and report writing (AI-augmentable)."),
    "2344": (5, "Geologists combine extensive fieldwork (physical — rock sampling, site assessment) with data interpretation and modelling (AI-augmentable)."),
    "2345": (6, "Life scientists combine laboratory research (physical) with data analysis, literature review, and publication (increasingly AI-augmentable)."),
    "2346": (4, "Medical laboratory scientists perform hands-on laboratory testing and analysis. While AI assists with interpretation, the physical sample handling and testing requires human presence."),
    "2347": (3, "Veterinarians perform hands-on animal examination, surgery, and treatment requiring physical presence and manual skill. AI may assist with diagnostics but cannot replace hands-on care."),
    "2349": (6, "Other science professionals typically combine physical research with digital analysis and reporting."),
    "2411": (4, "Early childhood teachers provide hands-on care, supervision, and education for young children. The interpersonal, caring, and physical presence requirements provide strong protection."),
    "2412": (5, "Primary school teachers deliver face-to-face education, manage classrooms, and provide pastoral care. AI can augment lesson planning and assessment, but in-person teaching and child development support remain essential."),
    "2413": (5, "Middle school teachers deliver face-to-face education with increasing subject specialisation. AI assists with content and assessment, but classroom management and mentoring require human presence."),
    "2414": (5, "Secondary school teachers deliver specialised subject education face-to-face. AI augments content delivery and assessment, but classroom interaction and student mentoring remain human."),
    "2415": (4, "Special education teachers provide individualised, often physical support for students with disabilities. The high interpersonal and adaptive care requirements provide strong protection."),
    "2421": (7, "University lecturers and tutors deliver knowledge-based education and conduct research — both increasingly AI-augmentable. Content delivery and research writing are highly digital, though mentoring and lab supervision are less exposed."),
    "2422": (6, "Vocational education teachers combine hands-on practical instruction (protected) with theory delivery and assessment (AI-augmentable)."),
    "2491": (7, "Education advisers perform curriculum development, policy analysis, and programme review — predominantly digital knowledge work that AI can significantly augment."),
    "2492": (6, "Private tutors provide personalised one-on-one instruction. AI tutoring systems are advancing but many students value human interaction. Exposure varies by subject."),
    "2493": (6, "TESOL teachers provide face-to-face language instruction with cultural and interpersonal elements. AI language tools are advancing rapidly but in-person teaching retains value."),
    "2511": (6, "Nutrition professionals combine scientific knowledge work (AI-augmentable) with client consultations and personalised health assessments requiring human interaction."),
    "2512": (5, "Medical imaging professionals operate complex equipment and interpret results. AI is advancing in image interpretation, but equipment operation and patient interaction require human presence."),
    "2513": (6, "Occupational and environmental health professionals combine site inspections (physical) with risk analysis and report writing (AI-augmentable)."),
    "2514": (4, "Optometrists perform hands-on eye examinations and patient care. While AI assists with diagnostics, the physical examination and patient interaction require human presence."),
    "2515": (5, "Pharmacists combine medication dispensing (increasingly automated) with patient counselling and clinical judgement that requires human interaction."),
    "2519": (5, "Other health diagnostic professionals combine hands-on patient assessment with analysis and reporting."),
    "2521": (3, "Chiropractors and osteopaths perform hands-on physical treatments requiring manual skill, patient assessment, and physical presence. AI has minimal impact on core treatment work."),
    "2522": (3, "Complementary health therapists provide hands-on treatments (massage, acupuncture, etc.) requiring physical presence and manual skill."),
    "2523": (3, "Dental practitioners perform intricate manual procedures in patients' mouths. While AI assists with diagnostics and treatment planning, the hands-on work is highly protected."),
    "2524": (4, "Occupational therapists provide hands-on patient assessment and treatment, adapting environments and activities. The physical and interpersonal components provide strong protection."),
    "2525": (3, "Physiotherapists perform hands-on physical treatments, exercise prescription, and patient assessment. The manual therapy and physical presence requirements provide strong protection."),
    "2526": (3, "Podiatrists perform hands-on foot examination and treatment. The physical nature of the work provides strong protection from AI disruption."),
    "2527": (4, "Audiologists and speech pathologists combine diagnostic testing (partially AI-augmentable) with hands-on therapy and patient interaction requiring human empathy and skill."),
    "2531": (4, "GPs perform physical examinations, patient consultations, and clinical decision-making. AI assists with diagnostics and record-keeping, but patient interaction and physical examination remain essential."),
    "2532": (3, "Anaesthetists perform critical hands-on medical procedures requiring real-time patient monitoring, physical presence, and rapid decision-making in high-stakes environments."),
    "2533": (4, "Specialist physicians combine clinical expertise with patient examination and complex diagnostic reasoning. AI assists with image interpretation and literature review, but hands-on patient care remains essential."),
    "2534": (4, "Psychiatrists provide therapy and medication management requiring deep interpersonal skills, empathy, and clinical judgement. While AI chatbots emerge, the therapeutic relationship remains fundamentally human."),
    "2535": (3, "Surgeons perform complex manual procedures requiring precise physical skills, real-time decision-making, and years of hands-on training. Robotic surgery assists but doesn't replace the surgeon."),
    "2539": (4, "Other medical practitioners perform hands-on patient care with varying degrees of diagnostic support from AI."),
    "2541": (3, "Midwives provide hands-on childbirth support, patient care, and emotional support in highly variable physical situations. The caring and physical presence components provide strong protection."),
    "2542": (7, "Nurse educators and researchers perform predominantly digital knowledge work — curriculum development, research, and publication — with some clinical teaching."),
    "2543": (6, "Nurse managers combine clinical oversight (requiring healthcare environment presence) with administrative and planning tasks (AI-augmentable)."),
    "2544": (3, "Registered nurses provide hands-on patient care, medication administration, and clinical monitoring. While AI assists with documentation and monitoring, the physical caring work is strongly protected."),
    "2611": (8, "ICT business and systems analysts perform digital analysis, requirements gathering, and documentation. AI can increasingly analyse systems, generate specifications, and identify improvements."),
    "2612": (9, "Multimedia specialists and web developers work entirely in digital creation — websites, apps, multimedia content. AI code generation and design tools are advancing extremely rapidly."),
    "2613": (9, "Software programmers work entirely in digital domains — writing, testing, and maintaining code. AI coding assistants are already transforming software development and will continue to do so."),
    "2621": (8, "Database administrators and ICT security specialists work entirely in digital infrastructure. AI is increasingly capable of monitoring, managing, and securing digital systems."),
    "2631": (7, "Computer network professionals manage digital infrastructure. While physical hardware work provides some protection, network design, monitoring, and troubleshooting are increasingly AI-augmented."),
    "2632": (7, "ICT support and test engineers perform digital testing and troubleshooting. AI-powered testing tools and automated diagnostics are rapidly advancing."),
    "2633": (6, "Telecommunications engineers combine digital design and analysis with physical infrastructure work. The physical component provides moderate protection."),
    "2711": (7, "Barristers perform legal research, argument preparation, and advocacy — largely digital knowledge work. AI can assist with research and drafting, though courtroom advocacy requires human presence."),
    "2712": (7, "Judicial and legal professionals perform legal analysis, decision-making, and case management — increasingly AI-augmentable, though judicial authority and human judgement remain essential."),
    "2713": (8, "Solicitors perform legal research, document drafting, contract review, and compliance work — predominantly digital tasks where AI is already making significant inroads."),
    "2721": (4, "Counsellors provide therapeutic support through deep interpersonal connection, empathy, and emotional intelligence. While AI chatbots are emerging, the human therapeutic relationship is difficult to replicate."),
    "2722": (3, "Ministers of religion provide spiritual guidance, community leadership, and pastoral care requiring deep personal connection and physical presence in communities."),
    "2723": (4, "Psychologists provide assessment, therapy, and clinical services requiring interpersonal skills, empathy, and clinical judgement. AI tools assist but cannot replace the therapeutic relationship."),
    "2724": (5, "Social professionals combine community engagement and relationship work (protected) with research, policy analysis, and documentation (AI-augmentable)."),
    "2725": (4, "Social workers provide direct client support, advocacy, and crisis intervention requiring empathy, relationship skills, and physical presence. Case documentation is AI-augmentable but core work is protected."),
    "2726": (4, "Welfare and community arts workers engage directly with communities through interpersonal programs and physical activities. The human connection component provides strong protection."),

    # === TECHNICIANS AND TRADES WORKERS (3xxx) ===
    "3111": (3, "Agricultural technicians perform hands-on fieldwork — soil testing, crop monitoring, and farm equipment operation. While AI assists with data analysis, physical work is protected."),
    "3112": (4, "Medical technicians perform hands-on laboratory and clinical procedures. AI assists with analysis but sample handling and equipment operation require human presence."),
    "3113": (3, "Primary products inspectors perform physical inspections of food, livestock, and agricultural products requiring hands-on assessment and presence."),
    "3114": (4, "Science technicians perform laboratory procedures and equipment operation. AI assists with data analysis but hands-on work is protected."),
    "3121": (5, "Architectural and surveying technicians combine digital drafting and modelling (AI-augmentable) with site measurement and inspection (physical)."),
    "3122": (6, "Civil engineering draftspersons produce technical drawings and documentation — increasingly AI-augmentable through CAD automation and generative design."),
    "3123": (6, "Electrical engineering draftspersons create technical drawings and specifications — digital work that AI-powered design tools can increasingly assist with."),
    "3124": (6, "Electronic engineering draftspersons work primarily with digital design tools. AI is advancing in circuit design and layout automation."),
    "3125": (6, "Mechanical engineering draftspersons produce technical drawings and specifications — digital work increasingly augmented by AI-powered CAD tools."),
    "3126": (3, "Safety inspectors perform physical site inspections requiring presence, observation, and hands-on assessment of workplace conditions."),
    "3129": (5, "Other building and engineering technicians combine technical documentation (AI-augmentable) with physical site work."),
    "3131": (6, "ICT support technicians troubleshoot and maintain computer systems. AI-powered diagnostics and remote management tools are increasingly capable, though physical hardware work provides some protection."),
    "3132": (5, "Telecommunications technical specialists combine physical equipment installation and maintenance with digital configuration and troubleshooting."),
    "3211": (2, "Automotive electricians perform hands-on diagnostic and repair work on vehicle electrical systems. The physical, dexterity-requiring work is highly protected from AI."),
    "3212": (2, "Motor mechanics perform hands-on vehicle diagnosis and repair requiring physical skill and problem-solving in variable conditions. AI assists with diagnostics but not physical repair."),
    "3221": (1, "Metal casting, forging, and finishing involves intensive hands-on work with heavy materials in industrial environments. AI has minimal impact on core physical tasks."),
    "3222": (1, "Sheetmetal trades involve hands-on cutting, bending, and fabricating metal components. The physical skill requirements provide very strong protection."),
    "3223": (1, "Structural steel and welding trades require hands-on welding, cutting, and fabrication in variable physical environments. Highly protected from AI disruption."),
    "3231": (2, "Aircraft maintenance engineers perform hands-on inspection, repair, and maintenance of aircraft. Safety-critical physical work with strong regulatory requirements."),
    "3232": (2, "Metal fitters and machinists perform hands-on fitting, turning, and machining operations. While CNC automation exists, skilled manual work remains essential."),
    "3233": (2, "Precision metal trades require fine manual skills for instrument making and repair. The exacting physical nature provides strong protection."),
    "3234": (2, "Toolmakers and patternmakers perform precise manual fabrication. While CNC assists, the skilled handwork and problem-solving remain human."),
    "3241": (1, "Panelbeaters perform hands-on vehicle body repair requiring manual skill, physical strength, and spatial judgement. Highly protected from AI."),
    "3242": (2, "Vehicle body builders and trimmers perform hands-on fabrication and fitting work requiring physical skill."),
    "3243": (2, "Vehicle painters perform physical spray painting requiring manual skill, surface preparation, and environmental control. Robots assist in factories but not in repair shops."),
    "3311": (1, "Bricklaying and stonemasonry are hands-on construction trades requiring physical strength, spatial awareness, and manual precision. Highly protected."),
    "3312": (1, "Carpentry and joinery involve hands-on construction work requiring manual skill, measurement, and physical labour on varied sites."),
    "3321": (1, "Floor finishing involves hands-on surface preparation, material laying, and finishing. Physical trade work with strong protection."),
    "3322": (1, "Painting trades involve physical surface preparation and paint application in varied environments. Manual skill and site presence required."),
    "3331": (1, "Glaziers install and repair glass in buildings — hands-on work requiring physical handling of heavy, fragile materials."),
    "3332": (1, "Plasterers apply and finish plaster and render — hands-on construction work requiring physical skill."),
    "3333": (1, "Roof tiling is physical outdoor work at heights, requiring manual skill and weather adaptation. Very highly protected."),
    "3334": (1, "Wall and floor tiling involves hands-on measurement, cutting, and laying of tiles. Physical trade work."),
    "3341": (2, "Plumbers install and maintain water and gas systems. Hands-on physical work in varied building environments. AI may assist with diagnostics but not physical pipe fitting."),
    "3411": (2, "Electricians install and maintain electrical systems. Physical hands-on work requiring safety awareness and manual skill. AI assists with diagnostics but not installation."),
    "3421": (2, "Airconditioning mechanics install and repair HVAC systems — hands-on physical work in varied environments."),
    "3422": (2, "Electrical distribution trades workers maintain power networks — physical outdoor work at heights with safety-critical requirements."),
    "3423": (3, "Electronics trades workers repair and maintain electronic equipment. Some diagnostic work is AI-augmentable, but hands-on repair requires physical skill."),
    "3424": (2, "Telecommunications trades workers install and maintain physical network infrastructure — cabling, equipment, and outdoor installations."),
    "3511": (1, "Bakers and pastrycooks perform hands-on food preparation requiring manual skill, timing, and sensory judgement (taste, texture, smell)."),
    "3512": (1, "Butchers perform hands-on meat cutting and processing requiring physical skill and food safety knowledge."),
    "3513": (2, "Chefs prepare food in fast-paced kitchen environments requiring manual skill, creativity, and real-time coordination. The physical and creative elements provide strong protection."),
    "3514": (1, "Cooks perform hands-on food preparation in commercial kitchens. Physical, time-pressured work with strong protection."),
    "3611": (2, "Animal attendants work hands-on with animals — feeding, grooming, exercising, and monitoring health. Physical presence with unpredictable animals is essential."),
    "3612": (1, "Shearing is intensive hands-on physical work with livestock in rural environments. Very highly protected from AI."),
    "3613": (3, "Veterinary nurses provide hands-on animal care, assisting with procedures and monitoring. Physical animal handling is essential, though record-keeping is AI-augmentable."),
    "3621": (2, "Florists create physical arrangements from natural materials requiring manual skill, creativity, and customer interaction."),
    "3622": (1, "Gardeners perform physical outdoor work — planting, pruning, mowing. Hands-on work in varied natural environments."),
    "3623": (1, "Greenkeepers maintain turf and grounds — physical outdoor work requiring hands-on care and environmental adaptation."),
    "3624": (1, "Nurserypersons propagate and maintain plants — hands-on horticultural work requiring physical presence and plant knowledge."),
    "3911": (2, "Hairdressers perform hands-on hair cutting, styling, and treatment. Physical work requiring manual skill and client interaction. Strongly protected."),
    "3921": (4, "Print finishers operate machines and perform manual finishing tasks. Some automation exists but skilled manual work and machine operation remain essential."),
    "3922": (7, "Graphic pre-press workers prepare digital files for printing. This digital workflow is increasingly automated through AI-powered tools."),
    "3923": (4, "Printers operate complex printing machinery. While digital printing advances, machine operation and maintenance require physical presence."),
    "3931": (1, "Canvas and leather goods makers perform hands-on fabrication requiring manual skill and craftwork."),
    "3932": (2, "Clothing trades workers perform hands-on garment construction. While industrial sewing is partially automated, skilled handwork remains essential."),
    "3933": (1, "Upholsterers perform hands-on furniture re-covering requiring manual skill and physical work."),
    "3941": (2, "Cabinetmakers construct and install furniture and fittings. Hands-on woodworking combining machine operation with manual skill."),
    "3942": (2, "Wood machinists operate woodworking machinery. While CNC assists, machine setup and operation require physical presence."),
    "3991": (2, "Boat builders construct and repair vessels — hands-on physical work requiring diverse manual skills."),
    "3992": (3, "Plant operators monitor and control chemical, gas, and power plant processes. AI assists with monitoring but physical presence for safety and maintenance is essential."),
    "3993": (5, "Gallery, library, and museum technicians combine physical collection handling with digital cataloguing and exhibition support."),
    "3994": (2, "Jewellers perform intricate hands-on work with precious materials requiring fine manual skill. Creative and physical work with strong protection."),
    "3995": (3, "Performing arts technicians operate physical equipment — lighting, sound, staging — requiring presence and real-time adaptation."),
    "3996": (3, "Signwriters create physical signs combining design (increasingly digital) with physical installation and fabrication."),
    "3999": (3, "Other miscellaneous technicians and trades workers typically perform hands-on physical work with varying degrees of digital support."),

    # === COMMUNITY AND PERSONAL SERVICE WORKERS (4xxx) ===
    "4111": (2, "Ambulance officers and paramedics provide emergency medical care in unpredictable, high-pressure physical environments. Hands-on clinical skills and rapid decision-making are essential."),
    "4112": (3, "Dental hygienists and technicians perform hands-on dental procedures and laboratory work. Physical patient contact and manual skill are essential."),
    "4113": (3, "Diversional therapists engage clients in hands-on activities and personal interaction. The interpersonal and physical activity components provide strong protection."),
    "4114": (3, "Enrolled nurses provide hands-on patient care including medication administration, wound care, and monitoring. Physical presence and caring skills are essential."),
    "4115": (3, "Indigenous health workers provide culturally specific health services requiring community trust, cultural knowledge, and personal relationships."),
    "4116": (2, "Massage therapists provide hands-on physical treatments. The manual, tactile nature of the work provides very strong protection from AI."),
    "4117": (3, "Welfare support workers provide direct client support, advocacy, and practical assistance. The interpersonal and community-based work is strongly protected."),
    "4211": (2, "Child carers provide hands-on supervision, care, and education for young children. Physical presence, safety supervision, and emotional nurturing are essential human tasks."),
    "4221": (3, "Education aides support teachers with hands-on student assistance, classroom management, and individual student support."),
    "4231": (2, "Aged and disabled carers provide hands-on personal care — bathing, dressing, feeding, mobility assistance. Physical caring work with strong protection."),
    "4232": (3, "Dental assistants provide hands-on chairside assistance during dental procedures. Physical presence and manual dexterity are essential."),
    "4233": (2, "Nursing support workers provide hands-on patient care — personal hygiene, mobility, feeding. Physical caring work that is strongly protected."),
    "4234": (2, "Special care workers provide hands-on support for people with disabilities or challenging behaviours in residential and community settings."),
    "4311": (2, "Bar attendants and baristas prepare drinks and serve customers. Physical food/beverage preparation and face-to-face customer interaction provide strong protection."),
    "4312": (2, "Cafe workers prepare food and serve customers. Hands-on food preparation and customer service in physical environments."),
    "4313": (5, "Gaming workers operate gaming machines and tables. Some tasks are automatable, but floor supervision and customer interaction require presence."),
    "4314": (4, "Hotel service managers combine guest-facing service (physical presence) with operational coordination (partially AI-augmentable)."),
    "4315": (2, "Waiters serve food and beverages, requiring physical presence, customer interaction, and real-time responsiveness."),
    "4319": (2, "Other hospitality workers perform hands-on food service, cleaning, and customer interaction tasks."),
    "4411": (2, "Defence force members perform physical military duties in varied and unpredictable environments. Hands-on skills and physical presence are essential."),
    "4412": (2, "Fire and emergency workers respond to emergencies requiring physical courage, hands-on rescue skills, and real-time decision-making in dangerous environments."),
    "4413": (3, "Police officers perform patrol, investigation, and community engagement requiring physical presence, interpersonal skills, and real-time judgement. AI assists with data analysis but not frontline policing."),
    "4421": (2, "Prison officers supervise inmates in custodial settings requiring physical presence, security awareness, and interpersonal management."),
    "4422": (2, "Security officers and guards provide physical security through presence, patrol, and access control. Human presence is the core function."),
    "4511": (2, "Beauty therapists provide hands-on treatments — facials, waxing, skin care. Physical, manual work with strong protection."),
    "4512": (2, "Driving instructors teach in-vehicle — requiring physical presence, real-time instruction, and adaptation to traffic conditions."),
    "4513": (2, "Funeral workers provide physical services — body preparation, ceremony management, and family support requiring empathy and presence."),
    "4514": (3, "Gallery, museum, and tour guides provide in-person interpretation and engagement. While AI audio guides exist, human interaction and storytelling add value."),
    "4515": (4, "Personal care consultants provide beauty and skincare advice. Online AI recommendations are growing, but in-person consultations and product demonstrations remain valued."),
    "4516": (7, "Tourism and travel advisers perform largely digital work — researching destinations, booking travel, and comparing options. Online booking platforms and AI assistants are rapidly displacing this role."),
    "4517": (2, "Travel attendants (flight attendants, etc.) provide in-flight/in-transit passenger service requiring physical presence, safety duties, and customer care."),
    "4518": (3, "Other personal service workers typically provide hands-on services requiring physical presence and interpersonal interaction."),
    "4521": (2, "Fitness instructors lead physical exercise sessions requiring demonstration, motivation, and real-time form correction. Physical presence and interpersonal energy are essential."),
    "4522": (1, "Outdoor adventure guides lead physical activities in natural environments — unpredictable terrain, weather, and safety management. Very strongly protected."),
    "4523": (2, "Sports coaches provide in-person physical training, technique instruction, and motivational leadership. The physical and interpersonal elements provide strong protection."),
    "4524": (1, "Sportspersons compete physically in athletic events. The physical performance is inherently human and cannot be replaced by AI."),

    # === CLERICAL AND ADMINISTRATIVE WORKERS (5xxx) ===
    "5111": (8, "Contract and project administrators perform digital documentation, scheduling, tracking, and reporting. AI project management tools are rapidly advancing."),
    "5121": (7, "Office managers coordinate administrative functions — scheduling, correspondence, filing — predominantly digital tasks increasingly augmented by AI."),
    "5122": (7, "Practice managers handle scheduling, billing, and administrative coordination — largely digital workflow management that AI can significantly augment."),
    "5211": (8, "Personal assistants manage calendars, correspondence, travel, and documents — predominantly digital tasks where AI assistants are rapidly improving."),
    "5212": (9, "Secretaries perform typing, correspondence, filing, and scheduling — routine digital tasks that AI can already handle at high quality."),
    "5311": (8, "General clerks perform routine administrative tasks — data entry, filing, correspondence, and record-keeping. These routine digital tasks are highly automatable."),
    "5321": (10, "Keyboard operators perform data entry and typing — routine, fully digital tasks that AI can already do faster and more accurately."),
    "5411": (9, "Call or contact centre workers handle customer queries by phone/chat. AI chatbots and voice systems are already replacing many of these functions."),
    "5412": (7, "Information officers provide information to the public — increasingly done through AI chatbots, automated systems, and self-service portals."),
    "5421": (7, "Receptionists greet visitors, manage calls, and coordinate bookings. Automated systems handle many of these functions, though some physical presence value remains."),
    "5511": (9, "Accounting clerks perform routine financial data entry, invoicing, and reconciliation — digital tasks highly suited to AI automation."),
    "5512": (8, "Bookkeepers maintain financial records, process transactions, and reconcile accounts — routine digital tasks increasingly automated by accounting software and AI."),
    "5513": (9, "Payroll clerks process payroll, calculate deductions, and maintain records — routine digital processing highly suited to automation."),
    "5521": (8, "Bank workers process transactions, manage accounts, and handle customer queries — largely automated through digital banking and AI."),
    "5522": (7, "Credit and loans officers assess applications and process loans. AI credit scoring and automated assessment are advancing, though complex cases require human judgement."),
    "5523": (8, "Insurance, money market, and statistical clerks perform routine data processing and record-keeping in financial services — highly automatable digital tasks."),
    "5611": (8, "Betting clerks process bets and calculate payouts — routine digital transactions increasingly automated."),
    "5612": (2, "Couriers and postal deliverers perform physical delivery work requiring navigation, vehicle operation, and package handling. While drones and autonomous vehicles are emerging, human delivery remains dominant."),
    "5613": (9, "Filing and registry clerks organise and retrieve physical and digital records — routine tasks that digital systems and AI can largely automate."),
    "5614": (9, "Mail sorters sort and distribute mail — routine physical/digital sorting tasks increasingly automated."),
    "5615": (8, "Survey interviewers collect data through structured questions — a task AI can perform through digital surveys, chatbots, and automated calling."),
    "5616": (10, "Switchboard operators route telephone calls — a function almost entirely automated by modern phone systems and AI."),
    "5619": (8, "Other clerical support workers perform routine digital administrative tasks — filing, data entry, correspondence — highly automatable."),
    "5911": (7, "Purchasing and supply clerks process orders, manage inventory, and coordinate logistics — increasingly automated through AI-powered procurement systems."),
    "5912": (6, "Transport and despatch clerks coordinate shipments and logistics. While digital coordination is AI-augmentable, physical warehouse presence may be required."),
    "5991": (8, "Conveyancers and legal executives perform document preparation, searches, and legal administration — routine legal tasks where AI is already making inroads."),
    "5992": (8, "Court and legal clerks manage case files, prepare documents, and maintain records — predominantly digital legal administration highly suited to AI."),
    "5993": (7, "Debt collectors contact debtors and negotiate payments. AI-powered automated calling and messaging systems are increasingly used, though complex negotiations remain human."),
    "5994": (8, "Human resource clerks process HR paperwork, maintain records, and handle routine queries — digital administrative tasks highly suited to AI automation."),
    "5995": (4, "Inspectors and regulatory officers perform physical inspections and compliance checks requiring on-site presence. Report writing is AI-augmentable but physical inspection is protected."),
    "5996": (5, "Insurance investigators combine field investigation (physical presence) with digital analysis and report writing."),
    "5997": (7, "Library assistants manage collections, process loans, and assist patrons — tasks increasingly automated through digital library systems and AI search."),
    "5999": (7, "Other miscellaneous clerical workers perform routine digital administrative tasks."),

    # === SALES WORKERS (6xxx) ===
    "6111": (5, "Auctioneers and stock agents combine in-person auctioneering (requiring presence and performance) with market analysis and client relationships."),
    "6112": (7, "Insurance agents sell policies and provide advice — increasingly done through comparison websites, AI recommendations, and automated underwriting."),
    "6113": (6, "Sales representatives combine relationship building and in-person client visits with digital communication and proposal preparation (AI-augmentable)."),
    "6121": (5, "Real estate agents combine property inspections and buyer/seller meetings (physical) with market analysis and marketing (increasingly AI-augmentable)."),
    "6211": (3, "Retail sales assistants provide in-store customer service, product advice, and transaction processing. Physical presence and interpersonal service remain important despite self-checkout growth."),
    "6212": (5, "ICT sales assistants combine technical product knowledge with in-store customer service. Online shopping and AI recommendations reduce but don't eliminate the need."),
    "6213": (4, "Motor vehicle salespersons provide in-person vehicle demonstrations, negotiations, and customer service. The high-value, physical product requires human interaction."),
    "6214": (3, "Pharmacy sales assistants provide in-person customer service and product advice in a health retail environment requiring human interaction."),
    "6215": (4, "Retail supervisors oversee store operations and staff — requiring physical presence while administrative tasks are AI-augmentable."),
    "6216": (2, "Service station attendants provide physical fuel service, shop sales, and site maintenance. Physical presence is essential."),
    "6217": (2, "Street vendors operate in physical outdoor environments requiring presence, customer interaction, and manual food/goods handling."),
    "6219": (4, "Other sales assistants provide in-person customer service with varying degrees of digital support."),
    "6311": (6, "Checkout operators process transactions — increasingly automated through self-checkout and contactless payment. Some customer interaction value remains."),
    "6391": (3, "Models and sales demonstrators provide physical product demonstrations and presentations requiring human presence."),
    "6392": (6, "Retail and wool buyers perform market analysis, price negotiation, and supply assessment — increasingly AI-augmentable through data analytics."),
    "6393": (9, "Telemarketers make outbound sales calls — a function increasingly performed by AI-powered calling systems and chatbots."),
    "6394": (7, "Ticket salespersons sell tickets for events and transport — largely automated through online booking platforms."),
    "6395": (6, "Visual merchandisers design retail displays. AI-powered design tools are advancing, though physical installation requires presence."),
    "6399": (5, "Other sales support workers perform various sales-related tasks with varying digital exposure."),

    # === MACHINERY OPERATORS AND DRIVERS (7xxx) ===
    "7111": (2, "Machine operators in manufacturing operate physical processing equipment requiring presence, monitoring, and manual adjustment."),
    "7112": (2, "Industrial spraypainters operate painting equipment in manufacturing environments. Physical operation and quality control require presence."),
    "7113": (2, "Paper and wood processing machine operators run physical production equipment requiring hands-on operation and monitoring."),
    "7114": (4, "Photographic developers and printers operate increasingly digital workflows. Traditional darkroom work is declining as digital processing and AI image tools advance."),
    "7115": (2, "Plastics and rubber machine operators run physical production equipment requiring hands-on operation, monitoring, and adjustment."),
    "7116": (2, "Sewing machinists operate industrial sewing machines. Physical garment production requiring manual skill and machine operation."),
    "7117": (2, "Textile and footwear machine operators run physical production equipment in manufacturing environments."),
    "7119": (2, "Other machine operators run various physical production equipment requiring presence and manual operation."),
    "7121": (2, "Crane, hoist, and lift operators control heavy lifting equipment requiring real-time spatial judgement and safety awareness. Physical presence is essential."),
    "7122": (1, "Drillers, miners, and shot firers work in underground and surface mining environments requiring physical presence in challenging, dangerous conditions."),
    "7123": (3, "Engineering production workers operate machinery and perform assembly tasks. Some automation exists but human oversight and manual work remain essential."),
    "7129": (2, "Other stationary plant operators monitor and control fixed industrial equipment requiring physical presence."),
    "7211": (2, "Agricultural plant operators operate tractors and farm machinery in varied outdoor conditions. GPS and automation assist but physical operation remains essential."),
    "7212": (2, "Earthmoving plant operators operate heavy equipment (excavators, bulldozers) in construction and mining. Physical operation in varied terrain requires human presence."),
    "7213": (2, "Forklift drivers operate forklifts in warehouses and worksites. While warehouse automation grows, human forklift operation remains widespread."),
    "7219": (2, "Other mobile plant operators control various mobile equipment requiring physical operation skills."),
    "7311": (3, "Automobile drivers (taxi, rideshare) transport passengers. Autonomous vehicles are developing but remain limited; human driving is still dominant."),
    "7312": (2, "Bus and coach drivers transport passengers on fixed routes. While autonomous bus trials exist, human drivers remain essential for safety and passenger assistance."),
    "7313": (3, "Train and tram drivers operate rail vehicles. Automated trains exist on some systems, but most still require human operators for safety."),
    "7321": (3, "Delivery drivers transport goods. Autonomous delivery is emerging but human drivers dominate, especially for varied delivery environments."),
    "7331": (2, "Truck drivers transport goods over long distances. While autonomous trucking is developing, human drivers remain essential for complex road conditions and loading/unloading."),
    "7411": (3, "Storepersons receive, store, and dispatch goods in warehouses. Warehouse automation is growing but human workers remain essential for varied tasks."),

    # === LABOURERS (8xxx) ===
    "8111": (1, "Car detailers perform hands-on vehicle cleaning and polishing. Manual physical work with strong protection."),
    "8112": (1, "Commercial cleaners clean buildings and facilities. Physical manual work requiring presence and adaptation to varied environments."),
    "8113": (1, "Domestic cleaners clean private homes. Physical work requiring manual skill and adaptation to varied environments."),
    "8114": (1, "Housekeepers maintain cleanliness and order in accommodation. Physical work requiring presence and manual skills."),
    "8115": (1, "Laundry workers process garments and linens. Physical handling work, though some industrial laundry processes are automated."),
    "8116": (1, "Other cleaners perform various physical cleaning tasks. Manual work with strong protection."),
    "8211": (1, "Building and plumbing labourers perform heavy physical construction work. Manual labour in varied site conditions."),
    "8212": (1, "Concreters prepare and pour concrete. Heavy physical work requiring manual skill and site presence."),
    "8213": (1, "Fencers install and repair fences. Physical outdoor work requiring manual skills."),
    "8214": (1, "Insulation and home improvement installers perform hands-on installation work. Physical trade assistance."),
    "8215": (1, "Paving and surfacing labourers perform heavy physical road and path construction."),
    "8216": (1, "Railway track workers maintain and construct rail infrastructure. Physical outdoor work in challenging conditions."),
    "8217": (1, "Structural steel construction workers erect steel frameworks. Heavy physical work at heights."),
    "8219": (1, "Other construction and mining labourers perform heavy physical work in varied conditions."),
    "8311": (1, "Food and drink factory workers perform hands-on food processing. Physical production work, though some factory processes are automated."),
    "8312": (1, "Meat boners and slicers perform hands-on meat cutting requiring physical skill and speed."),
    "8313": (1, "Meat, poultry, and seafood process workers perform physical food processing tasks."),
    "8321": (1, "Packers manually package products for distribution. Physical handling work."),
    "8322": (2, "Product assemblers assemble manufactured goods. Some assembly is automated but many tasks require manual dexterity."),
    "8391": (2, "Metal engineering process workers assist in metal manufacturing. Physical production work with some machine operation."),
    "8392": (2, "Plastics and rubber factory workers perform physical production tasks."),
    "8393": (3, "Product quality controllers inspect manufactured goods. AI-powered visual inspection is advancing, but physical handling and assessment remain important."),
    "8394": (1, "Timber and wood process workers perform physical wood processing tasks."),
    "8399": (2, "Other factory process workers perform various physical production tasks."),
    "8411": (1, "Aquaculture workers perform physical work with fish and aquatic stock in outdoor/water environments."),
    "8412": (1, "Crop farm workers perform physical agricultural labour — planting, weeding, harvesting."),
    "8413": (1, "Forestry and logging workers perform physical work in remote forest environments. Heavy manual work with strong protection."),
    "8414": (1, "Garden and nursery labourers perform physical horticultural work — digging, planting, watering."),
    "8415": (1, "Livestock farm workers perform physical animal husbandry tasks — feeding, mustering, fencing."),
    "8416": (1, "Mixed crop and livestock farm workers perform varied physical agricultural labour."),
    "8419": (1, "Other farm, forestry, and garden workers perform physical outdoor agricultural work."),
    "8511": (1, "Fast food cooks prepare food quickly in commercial kitchens. Physical, fast-paced manual work."),
    "8512": (1, "Food trades assistants support food preparation. Physical kitchen work."),
    "8513": (1, "Kitchenhands wash dishes, clean kitchens, and assist with food preparation. Physical manual work."),
    "8911": (1, "Freight and furniture handlers load, unload, and move heavy items. Physical manual labour."),
    "8912": (2, "Shelf fillers stock shelves in retail environments. Physical work, though some warehouse automation is emerging."),
    "8991": (1, "Caretakers maintain buildings and grounds. Physical maintenance work requiring presence."),
    "8992": (1, "Deck and fishing hands work on vessels performing physical tasks in marine environments. Physically demanding outdoor work."),
    "8993": (1, "Handypersons perform various physical repair and maintenance tasks in buildings."),
    "8994": (2, "Motor vehicle parts fitters install vehicle parts and accessories. Hands-on physical work."),
    "8995": (3, "Printing assistants operate printing machinery. Some print production is digitally streamlined, but physical machine operation remains."),
    "8996": (1, "Recycling and rubbish collectors perform physical waste collection and sorting in varied outdoor conditions."),
    "8997": (2, "Vending machine attendants stock and maintain vending machines. Physical routine work."),
    "8999": (1, "Other miscellaneous labourers perform various physical manual tasks."),
}


def main():
    with open("occupations.json") as f:
        occupations = json.load(f)

    scores = []
    missing = []

    for occ in occupations:
        anzsco = occ["anzsco"]
        if anzsco in SCORES:
            exposure, rationale = SCORES[anzsco]
            scores.append({
                "slug": occ["slug"],
                "title": occ["title"],
                "exposure": exposure,
                "rationale": rationale,
            })
        else:
            missing.append(anzsco)

    with open("scores.json", "w") as f:
        json.dump(scores, f, indent=2)

    print(f"Scored {len(scores)} occupations")
    if missing:
        print(f"Missing scores for {len(missing)} occupations: {missing}")

    # Stats
    avg = sum(s["exposure"] for s in scores) / len(scores)
    by_score = {}
    for s in scores:
        bucket = s["exposure"]
        by_score[bucket] = by_score.get(bucket, 0) + 1

    print(f"\nAverage exposure: {avg:.1f}")
    print("Distribution:")
    for k in sorted(by_score):
        print(f"  {k}: {'█' * by_score[k]} ({by_score[k]})")


if __name__ == "__main__":
    main()
